### ISSUE TITLE
Module '"astro:db"' has no exported member 'Signup'

### ISSUE THREAD

**Issue by mysticeti** [withastro/studio-templates#42]
Hi

Template name - astro-waitlist-template
I am getting the following error in all the .astro files that tries to import the Signup table even in the db/seed.ts the issue is there
`Module '"astro:db"' has no exported member 'Signup'`

I would really appreicate any help regarding this. I did not change anything, the basic template is having the issue to begin with.

**Comment by ElianCodes** [comment]
Hey there! This is very likely just a small issue with your IDE. The Astro DB types only get generated once the devserver is started.
So, if you run `astro dev`, this issue should be resolved automatically!

Please keep me updated if this is not the case.
